### ISSUE TITLE
Code snippets parsed incorrectly and throw errors when not running in project directory

### ISSUE THREAD

**Issue by WillBartee** [snyk/snyk-to-html#128]
## Current Behavior
Multiple errors are printed to the console for each vulnerability when running `snyk-to-html` outside of the scanned projects root directory and using the output of `snyk code test...`.

In addition to the errors, the "Data Flow" portion of the resulting HTML does not correctly display the vulnerable code.

## Tested versions
- snyk-to-html:
  - v2.3.2
- snyk:
  - _shouldn't matter_

## How to Reproduce
```shell
npm install -g snyk-to-html@latest
mkdir scratch
cd scratch
npm init -y
npm install axios
cat <<EOF > index.js
import axios from 'axios'

function fail(req, res) {
  return res.status(401).send(req.query)
}
EOF
snyk code test --json > ../snyk.json
cd ..
snyk-to-html -i snyk.json -o snyk.html
```

## Example Output
```text
$ snyk-to-html -i snyk.json -o results.html
[Error: ENOENT: no such file or directory, open '/Users/will/workspaces/index.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/will/workspaces/index.js'
}
[Error: ENOENT: no such file or directory, open '/Users/will/workspaces/index.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/will/workspaces/index.js'
}
[Error: ENOENT: no such file or directory, open '/Users/will/workspaces/index.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/will/workspaces/index.js'
}
[Error: ENOENT: no such file or directory, open '/Users/will/workspaces/index.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/will/workspaces/index.js'
}
Vulnerability snapshot saved at results.html
```
<img width="904" alt="Screen Shot 2022-05-09 at 4 20 12 PM" src="https://user-images.githubusercontent.com/4605970/167513855-ed05aac1-3b1f-4489-a021-a12730953f6b.png">

## Expected/Desired Behavior
- _Bug Report_ - Errors aren't displayed on handled exceptions.
- _Support Request_ - HTML output doesn't include invalid code snippets. (Without the need for custom templates)
- _Feature Request_ - Option to specify the `uriBaseId` referenced in the SARIF output as `%SRCROOT%`

**Comment by cmanaila60** [comment]
+1 
Versions:
snyk-to-html: v2.3.2
snyk: 1.790.0

I am seeing the same behavior. Although the previous version of snyk-to-html didn't have this issue **2.3.1**

```
snyk code test scan_folder/ --sarif | snyk-to-html > report-code.html
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/Desktop/work/repos/salesforce/JiraIntegration.cls'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:147:14
    at FSReqCallback.oncomplete (fs.js:171:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/Desktop/work/repos/salesforce/JiraIntegration.cls'
}
```
